### ISSUE TITLE
Update git ref for singularity

### ISSUE THREAD

**Issue by EdHurtig** [evertrue/singularity-cookbook#5]
Singularity has had a nasty bug patched in revision [dfc4b0ddf1643bca80d4341b2bffd476b375d627](https://github.com/HubSpot/Singularity/commit/dfc4b0ddf1643bca80d4341b2bffd476b375d627).

**Comment by EdHurtig** [comment]
Putting this here to remember for tomorrow when a new release for Singularity is supposed to be cut

**Comment by jeffbyrnes** [comment]
@EdHurtig @eherot we should def. get this rolled out ASAP.

**Comment by EdHurtig** [comment]
this was handled in v2.0.0
